FROM mcr.microsoft.com/dotnet/sdk:8.0 AS build

WORKDIR /src

COPY NotificationService.csproj .

RUN dotnet restore

COPY . .

RUN dotnet publish -c Release -o /app/publish

FROM mcr.microsoft.com/dotnet/aspnet:8.0

WORKDIR /app

COPY --from=build /app/publish .

ENTRYPOINT ["dotnet", "NotificationService.dll"]